import Link from "next/link";
import type { Metadata } from "next";
import { SiteNav } from "@/components/site-nav";

export const metadata: Metadata = {
  title: "VideoForge — Turn ideas into finished videos",
  description: "Plan scripts, scenes, narration, captions, and renders in one adaptable video-production workspace.",
};

const features = [
  ["Script workspace", "Bring your outline into a structured, reviewable script before any production work starts."],
  ["Scene planning", "Turn a story into an ordered visual plan with room for your own creative direction."],
  ["Flexible providers", "Keep AI, voice, and media tools behind interchangeable interfaces as your workflow evolves."],
  ["Render job tracking", "Treat long-running work as visible jobs with progress, retries, and meaningful errors."],
  ["Private projects", "Project ownership and private media are designed around secure access controls from the outset."],
  ["Creator-ready metadata", "Prepare titles, descriptions, tags, and thumbnails beside the video rather than after it."],
];

const questions = [
  ["Is VideoForge already generating videos?", "Not yet. The current product preview shows sample interface states only. Video generation, voice, and rendering will be introduced in clearly labelled phases."],
  ["Can I choose my own AI or voice provider?", "Yes. VideoForge is designed with provider interfaces so script, image, video, voice, and transcription services can be changed without rebuilding the workspace."],
  ["Does rendering happen in the browser?", "No. The app separates long-running render work into an independent worker, which keeps the web experience responsive and makes local development practical."],
  ["Can I use it on mobile?", "Yes. Project management, dashboard, settings, and basic creation paths are designed to remain usable on smaller screens. Full editing is optimized for desktop."],
];

export default function Home() {
  return <><SiteNav /><main>
    <section className="landing-hero shell" aria-labelledby="hero-title"><div className="hero-copy"><div className="eyebrow">A free-first production workspace</div><h1 id="hero-title">Turn an idea into a finished video.</h1><p>Move from a topic to <strong>script → scenes → voice → captions → render</strong> in one calm, flexible creative workflow.</p><div className="hero-actions"><Link className="vf-button primary" href="/signup">Create a Video <span aria-hidden="true">→</span></Link><Link className="vf-button secondary" href="/dashboard">Explore Demo</Link></div><p className="hero-note">No credit card. Product preview uses sample content only.</p></div><div className="hero-orbit" aria-label="Sample VideoForge project interface"><div className="preview-glow" /><div className="preview-window"><div className="preview-bar"><span className="preview-dots"><i /><i /><i /></span><span>Project studio</span><span className="vf-badge">Sample</span></div><div className="preview-layout"><div className="preview-rail"><span className="rail-active" /><span /><span /><span /></div><div className="preview-stage"><div className="preview-video"><span className="preview-play">▶</span><div className="preview-caption">Small choices shape the world around us.</div></div><div className="preview-timeline"><span /><span /><span /><span /></div></div></div></div><div className="floating-card card-script"><span>Script</span><strong>4 scenes ready</strong><small>Sample preview</small></div><div className="floating-card card-render"><span className="status-dot" /> Render pipeline<br /><strong>Waiting for worker</strong></div></div></section>

    <section className="landing-section shell product-preview" aria-labelledby="preview-title"><div className="section-heading"><div><div className="eyebrow">One focused workspace</div><h2 id="preview-title">The production view, without the production chaos.</h2></div><p>Every stage has a clear purpose: make decisions early, track the work that follows, and keep outputs connected to the project.</p></div><div className="product-board panel"><div className="board-sidebar"><span className="board-logo">V</span><span className="board-nav active">Overview</span><span className="board-nav">Script</span><span className="board-nav">Scenes</span><span className="board-nav">Audio</span></div><div className="board-content"><div className="board-top"><div><strong>Mindful systems</strong><small>Interface preview · not a live project</small></div><span className="vf-badge warning">Draft</span></div><div className="board-columns"><div className="board-story"><div className="mini-label">Story outline</div><div className="story-line wide" /><div className="story-line" /><div className="story-line mid" /><div className="story-block"><span>Scene 01</span><strong>A practical opening</strong><small>00:00 — 00:14</small></div><div className="story-block"><span>Scene 02</span><strong>Introduce the shift</strong><small>00:14 — 00:28</small></div></div><aside className="board-status"><div className="mini-label">Production status</div><div className="status-item"><span /> Script outline <b>Ready</b></div><div className="status-item muted"><span /> Visual assets <b>Next</b></div><div className="status-item muted"><span /> Render output <b>Queued</b></div></aside></div></div></div></section>

    <section className="landing-section shell" aria-labelledby="how-title"><div className="section-heading centered"><div className="eyebrow">A deliberate path</div><h2 id="how-title">From an empty note to a production-ready plan.</h2><p>VideoForge keeps the creative steps visible and separates them from long-running technical work.</p></div><ol className="how-grid">{[["01", "Start with a topic", "Capture the idea, audience, pace, and format before you write."], ["02", "Shape the narrative", "Review a script and turn it into a scene-by-scene visual plan."], ["03", "Build the media", "Attach visuals, voice, captions, music, and other production inputs."], ["04", "Render with confidence", "Send an approved plan to the worker and follow its progress." ]].map(([num, title, text]) => <li key={num}><span>{num}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>

    <section className="landing-section feature-band" aria-labelledby="features-title"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Designed for changing tools</div><h2 id="features-title">A practical system that grows with your process.</h2></div><p>Use free tiers and local tooling where they fit. Swap providers when the work calls for something else.</p></div><div className="feature-grid">{features.map(([title, text], index) => <article className="feature-card panel" key={title}><span className="feature-index">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="landing-section shell" aria-labelledby="workflow-title"><div className="workflow-card panel"><div className="workflow-copy"><div className="eyebrow">A clear technical boundary</div><h2 id="workflow-title">Keep the creative flow fast. Send the heavy work elsewhere.</h2><p>VideoForge treats rendering as a job, not a browser request. That makes failures understandable, retries possible, and a local worker easy to start with.</p><Link href="/dashboard" className="vf-button secondary">See the workspace</Link></div><div className="workflow-diagram" aria-label="VideoForge workflow: Browser to application to job system to worker to finished output"><div>Idea</div><i>→</i><div>Project plan</div><i>→</i><div>Render job</div><i>→</i><div className="diagram-worker">Worker</div><i>→</i><div className="diagram-output">Video</div></div></div></section>

    <section className="landing-section shell" aria-labelledby="examples-title"><div className="section-heading"><div><div className="eyebrow">Sample project directions</div><h2 id="examples-title">A starting point for every kind of faceless story.</h2></div><p>These are creative examples, not generated outputs.</p></div><div className="examples-grid">{[["The physics of everyday calm", "Explainer", "06 scenes · 90 sec", "lavender"], ["Tiny routines, lasting change", "Self development", "08 scenes · 2 min", "cyan"], ["A map of the night sky", "Education", "05 scenes · 75 sec", "amber"]].map(([title, type, meta, color]) => <article className="example-card panel" key={title}><div className={`example-cover ${color}`}><span>Sample concept</span><b>▶</b></div><div className="example-body"><span>{type}</span><h3>{title}</h3><p>{meta}</p></div></article>)}</div></section>

    <section className="landing-section shell faq-section" aria-labelledby="faq-title"><div className="section-heading centered"><div className="eyebrow">Questions, answered</div><h2 id="faq-title">Build clearly, not mysteriously.</h2></div><div className="faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>

    <section className="landing-section shell"><div className="cta-card"><div><div className="eyebrow">Start with the idea</div><h2>Make your next video workflow feel intentional.</h2><p>Explore the workspace today, then add the providers and worker setup that fit your production style.</p></div><div className="hero-actions"><Link className="vf-button primary" href="/signup">Create a Video →</Link><Link className="vf-button secondary" href="/dashboard">Explore Demo</Link></div></div></section>
  </main><footer className="landing-footer"><div className="shell"><div><span className="brand"><span className="mark" />VideoForge</span><p>Flexible video production, built one clear step at a time.</p></div><nav aria-label="Footer"><Link href="/templates">Templates</Link><Link href="/dashboard">Demo</Link><Link href="/settings">Settings</Link></nav><small>© {new Date().getFullYear()} VideoForge</small></div></footer></>;
}
